### ISSUE TITLE
[v0.4.5.3] No wheels (including ffms2-lib) available for Python other than v3.7-x64

### ISSUE THREAD

**Issue by e-d-n-a** [bubblesub/pyffms2#25]
Latest [PyPI-package](https://pypi.org/project/ffms2/#files) only provides a wheel for Python v3.7-x64.

Installation in a newer Python version uses source-package (.tar.gz) [see #24], that is missing the "ffms2"-lib and there is no documentation how to install it manually!

**Running "test.py" gives following error:**
```
>python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    import ffms2
  File "C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\lib\site-packages\ffms2\__init__.py", line 33, in <modu
le>
    from .libffms2 import *
  File "C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\lib\site-packages\ffms2\libffms2.py", line 9, in <modul
e>
    lib = get_library(
  File "C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\lib\site-packages\ffms2\get_library.py", line 44, in ge
t_library
    raise OSError("can't find {!r} library".format(lib_name))
OSError: can't find 'ffms2' library
```

I could solve this myself by copying the files of the [latest binary release of ffms2](https://github.com/FFMS/ffms2/releases/download/2.40/ffms2-2.40-msvc.7z) into the package (at "C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\Lib\site-packages\ffms2").

**There are 2 newer major Python releases already available, which should get supported:**

- Python v3.8.7.0-x64
- Python v3.9.1.0-x64

**Comment by rr-** [comment]
Is there a particular reason why you are using exclamation marks? Pull requests are welcome.

**Comment by rr-** [comment]
Also pinging @Luni-4 as he's the most knowledgeable in packaging (#24 might be of relation)

**Comment by Luni-4** [comment]
Hello @e-d-n-a and thanks for your issues! :)

Actually we are packaging ffms2 just for `Python 3.7`, as you can see from [here](https://github.com/bubblesub/pyffms2/blob/master/.github/workflows/deploy-binaries.yml#L259), but we can always bump our binaries, being at the same time, backward compatible.

Feel free to fiddle with the `deploy-binaries.yml` file in your fork and try to create a new working package, then, as @rr- said, pull requests are welcome.

**Comment by e-d-n-a** [comment]
OK, thx for the link, but I'm no expert in creating bindings. I cannot see any explanation in there.
Is this binding package in any way specific to Python v3.7 and is not supposed to work with Python v3.8, v3.9, ...?

**Comment by Luni-4** [comment]
I've used `Python 3.7` to create those bindings, but since you can run them on `Python 3.9`, from your logs, I guess we should update the tags [here](https://github.com/bubblesub/pyffms2/blob/master/.github/workflows/deploy-binaries.yml#L278) to `3.8` and `3.9` too. Anyway, the `ffms2` binaries should work with any `Python` version.

**Comment by e-d-n-a** [comment]
Small correction - I tested using "Python v3.8.7.0":
> Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32

I can also check real quick, if it works in Python v3.9.1.0, but I was about to first test some basic functionality using my fixed installation in Python v3.8.7.0 to make sure it's usable.

**Comment by Luni-4** [comment]
Yep, check it out then!

**Comment by rr-** [comment]
@Luni-4 do I understand it correctly that GitHub actions will automatically build and publish the package on PyPI, working for all relevant versions, after I push a tag on the latest master?

**Comment by Luni-4** [comment]
@rr- 

Exactly, we have added [this](https://github.com/bubblesub/pyffms2/blob/master/.github/workflows/deploy-binaries.yml#L282) line just to avoid publishing botched versions.

**Comment by rr-** [comment]
OK, I bumped the version, let's see what happens – fingers crossed. Also I added a note for myself to this repository's README to avoid nagging you with this question every time :sweat_smile:

**Comment by Luni-4** [comment]
We have to replace the `nasm` step with ` - uses: ilammy/setup-nasm@v1` in this way we always have an updated nasm

**Comment by rr-** [comment]
Oh, I noticed your comment only now – I resolved this by bumping the version manually. Shouldn't matter though

**Comment by Luni-4** [comment]
@e-d-n-a 

Could you please verify whether the new version fixes this issue?

**Comment by e-d-n-a** [comment]
Well, this issue is about missing wheels for higher Python versions and I can't see any new wheels being provided with [v0.4.5.4](https://pypi.org/project/ffms2/#files).

This new version just fixes the "pythoncom"-import issue (see #27).
I found out about the requirement for ["pypiwin32" on Windows is coming from "setup.py](https://github.com/bubblesub/pyffms2/blob/2b2f6e82268c8fed98021d4148238027ac2986fe/setup.py#L9)", that is used for the source-package.

So installation is still broken on Windows due to missing ffms2-files (this issue) and #26.

I haven't tested if the (recommended) installation via "setup.py" works, when down manually and [providing the ffms2-files beforehand alongside "setup.py](https://github.com/bubblesub/pyffms2/blob/2b2f6e82268c8fed98021d4148238027ac2986fe/setup.py#L14)" (so basically a GitHub-Installation).

**I personally would appreciate a working installation process via "pip" using the files from PyPI.**

**Comment by rr-** [comment]
@Luni-4 
Shouldn't we amend this file `.github/workflows/deploy-binaries.yml`
the line with
```
python setup.py bdist_wheel --plat-name win_amd64 --python-tag cp37
```
to include `cp38` and `cp39`?

**Comment by Luni-4** [comment]
@rr- 

Yep, but IIRC, it didn't work. First we need to update [this](https://github.com/bubblesub/pyffms2/blob/2b2f6e82268c8fed98021d4148238027ac2986fe/.github/workflows/deploy-binaries.yml#L254) this line to `3.9` to have the respective tags.

**Comment by rr-** [comment]
Pushed 0.4.5.5 with the new wheels distribution, fingers crossed…

**Comment by rr-** [comment]
@Luni-4 @e-d-n-a can you confirm if the newest release meets your requirements?

**Comment by e-d-n-a** [comment]
**I tested it with a Py-3.7 and a Py-3.8 environment.**

In both cases "ffms2-0.4.5.5-cp37.cp38.cp39-none-win_amd64.whl" was used for the installation,
but [see my post here](https://github.com/bubblesub/pyffms2/issues/24#issuecomment-783314214) for details on the results (1 issue left)!

**Comment by Luni-4** [comment]
Since this issue has been fixed, we can talk about the last remaining problems in the other thread
