### ISSUE TITLE
[v0.4.5.3] Pyffms2 uses "pypiwin32" as a dependency instead of newer and compatible "pywin32"

### ISSUE THREAD

**Issue by e-d-n-a** [bubblesub/pyffms2#26]
> Pypiwin32 is an old and outdated repackaging of pywin32 from its creator to use wheels.
> It is abandoned for a long time. You should just use pywin32.

**Src:** https://stackoverflow.com/a/55918399/14658777

**As "[pywin32](https://pypi.org/project/pywin32/)" is used these days and is often already installed, pyffms2 should not install "[pypiwin32](https://pypi.org/project/pypiwin32/)"!**

See #24 for an installation-log.

Simple tests to import "pythoncom" or "win32api" failed with "pypiwin32" installed,
```
<C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\Lib\site-packages\ffms2:
>python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythoncom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pythoncom'
>>> import atexit
>>> import pythoncom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pythoncom'
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
>>> exit()
```
 but worked fine with "pywin32" installed!
```
<C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\Lib\site-packages\ffms2:
>python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
>>> import pythoncom
>>> exit()
```

**I uninstalled "pypiwin32" and fixed #27 to use "pythoncom" correctly, that comes with "pywin32".
After that everything (test.py) worked just fine so far!**

**Comment by Luni-4** [comment]
I don't have any problem switching to `Python 3.8`, in this way you can convert your fixes into a PR. I will be happy to review it. Any thoughts @rr- about the minimal Python version?

**Comment by e-d-n-a** [comment]
On [PyPI](https://pypi.org/project/ffms2/) under "Prerequisites" it's stated that the package is compatible with "Python 3.2+".
Although the whole description seems to be copy of the [old package](https://pypi.org/project/ffms/). Maybe something has changed since then!?

**Comment by Luni-4** [comment]
> On [PyPI](https://pypi.org/project/ffms2/) under "Prerequisites" it's stated that the package is compatible with "Python 3.2+".
> Although the major part of the description seems to be copied from the [old package](https://pypi.org/project/ffms/).
> Maybe something has changed that since then!?

True, I propose to write "Python 3.7+", since we have tested these bindings with those versions

**Comment by rr-** [comment]
Not sure why this was closed. Can you please confirm if the newest changes are satisfactory? @e-d-n-a

**Comment by e-d-n-a** [comment]
Well, as I just started to familiarize myself with ffms2 and pyffms2, I'm not the one able to judge the compatibility with different Python versions, yet.

### Testing of pyffms2 with Python 3.8.7
I continued to test with Python 3.8 on Windows and everything seems to work fine there.
I could create indices, check properties and grab frames by number and time very fast and reliably.
I tested different file formats and codecs and only WEBM/VP9 gave me inaccurate results.
I haven't tested more yet, but everything from now on would be more likely related to the ffms2-package, that I'm using and not the python-bindings. 

That Python 3.9 should work as well is not the question here.

### Pywin32
This issue is actually about "pypiwin32" and my suggestion to replace it with "[pywin32](https://pypi.org/project/pywin32/)", which is available for Python 3.5+.
So someone should check what language features are used in this project, that might lower the version compatibility in comparison to "pywin32".
I checked the pyffms2-packages available on PyPI again for v0.4.5.3 and v0.4.5.4 and cannot see "pywin32" set as a requirement.
It installed "pypiwin32" for me before in Python 3.8.7, but now doesn't in Python 3.7.6:
```
<C:\WinPython\WPy-x64-3760ps2\scripts:
>pip install ffms2
Collecting ffms2
  Downloading ffms2-0.4.5.4-cp37-none-win_amd64.whl (35.8 MB)
     |████████████████████████████████| 35.8 MB 6.8 MB/s
Requirement already satisfied: numpy in c:\winpython\wpy-x64-3760ps2\python-3.7.6.amd64\lib\site-packages (f
rom ffms2) (1.17.4+mkl)
Installing collected packages: ffms2
Successfully installed ffms2-0.4.5.4
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\WinPython\WPy-x64-3760ps2\python-3.7.6.amd64\python.exe -m pip ins
tall --upgrade pip' command.
```

### Minimal Python version
Python 3.5 and Python 3.6 probably still have a significant usage percentage (market share) and should not be neglected so easily:
[Usage statistics of Python Version 3 for websites](https://w3techs.com/technologies/details/pl-python/3)

**Comment by e-d-n-a** [comment]
OK, I now saw that "setup.py", which gets executed, when installing from the source package, still would install "pypiwin32".

[See here](https://github.com/bubblesub/pyffms2/blob/2b2f6e82268c8fed98021d4148238027ac2986fe/setup.py#L9).

**Comment by Luni-4** [comment]
> Well, as I just started to familiarize myself with ffms2 and pyffms2, I'm not the one able to judge the compatibility with different Python versions, yet.
> ### Testing of pyffms2 with Python 3.8
> 
> I continued to test with Python 3.8.7 on Windows and everything seems to work fine there.
> I could create indices, check properties and grab frames by number and time very fast and reliably.
> I tested different file formats and codecs and only WEBM/VP9 gave me inaccurate results so far.
> I haven't tested more yet, but everything from now on would be more likely related to the ffms2-package, that I'm using and not the python-bindings.

Yes, those problems are not related to bindings, but to the `ffms2` package instead.

> ### Pywin32
> 
> This issue is actually about "pypiwin32" and my suggestion to replace it with "[pywin32](https://pypi.org/project/pywin32/)", which is available for Python 3.5+.
> So someone should check what language features are used in this project, that might lower the version compatibility in comparison to "pywin32".
> I checked the pyffms2-packages available on PyPI again for v0.4.5.3 and v0.4.5.4 and cannot see "pywin32" set as a requirement.
> It installed "pypiwin32" for me before in Python 3.8.7 (see #24), but now doesn't in Python 3.7.6:
> 

We haven't added `pywin32`, feel free to send a PR anytime though :)

> 
> Have you changed the requirements (besides the Python version)?
> ### Minimal Python version
> 
> Python 3.5 and Python 3.6 probably still have a significant usage percentage (market share) and should not be neglected so easily:
> [Usage statistics of Python Version 3 for websites](https://w3techs.com/technologies/details/pl-python/3)

Looking at those statistics, I would support from `Python 3.6+`. Any thoughts @rr-?

**Comment by e-d-n-a** [comment]
Why do you need a PR to remove 2 characters from a file (setup.py)?
It's more about, if you agree to use "pywin32" instead of "pypiwin32".

**Comment by rr-** [comment]
A pull request will trigger a CI test suite (including Windows) but if you're unwilling to create one I will do it.

**Comment by rr-** [comment]
The CI has succeeded and the change is now on master, but I'll only release a new version once we sort out the distribution of wheels in the other ticket.

**Comment by Luni-4** [comment]
@rr- 

Add `Python 3.6` below [here](https://github.com/bubblesub/pyffms2/blob/master/setup.py#L31) please, so this issue is complete
