### ISSUE TITLE
[v04.5.3] Fix for pythoncom-import issue not included in latest release, but already in master

### ISSUE THREAD

**Issue by e-d-n-a** [bubblesub/pyffms2#27]
After an installation (see #24) the "test.py" throws the following error:
```
<C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\Lib\site-packages\ffms2:
>python test.py
.
----------------------------------------------------------------------
Ran 1 test in 0.094s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\WinPython\WPy-x64-3870\python-3.8.7.amd64\lib\site-packages\ffms2\__init__.py", line 207, in ffms
_uninit
    pythoncom.CoUninitialize()
NameError: name 'pythoncom' is not defined
```

**The issue is caused by "pythoncom"-module no being available globally after import in "ffms_init()".**

I fixed it myself by adding the following line at the beginning of "ffms_init()" in file "\_\_init\_\_.py":
```
    def ffms_init():
        global pythoncom  # also allow access to pythoncom from within ffms_uninit()
        [...]
```

I checked the source from the source-release and Py3.7-x64-wheel [available on PyPI](https://pypi.org/project/ffms2/#files). Both contain "ffms_uninit()" in this form:
```
    def ffms_uninit():
        pythoncom.CoUninitialize()
        pythoncom._initialized = False
```
[(see in source here on GitHub)](https://github.com/bubblesub/pyffms2/blob/3829d259c41e0721703fd1d6f13bb5b5bba9b036/ffms2/__init__.py#L206)

I checked the "master" also, as I couldn't believe this problem has been unnoticed, and found this:
```
    def ffms_uninit():
        import pythoncom
        
        pythoncom.CoUninitialize()
        pythoncom._initialized = False
```
[(see in source here on GitHub)](https://github.com/bubblesub/pyffms2/blob/6158e036e2958e97ae8753abb03bc72fecc5ba45/ffms2/__init__.py#L206)

**So it's solved in master, but not included in the latest release!!**

**Comment by Luni-4** [comment]
This one could be solved bumping a new release right now (https://github.com/bubblesub/pyffms2/commit/7e7e89f050218eac470213d65e4350c89d7ccf10#diff-db04a7e018b54db748a6b5ff09a7ce8d9389c5c648b096e6eb0d70839f7e011cR207). Could you please do that @rr-?

**Comment by Luni-4** [comment]
@e-d-n-a 

Could you please verify if the new version fixes this issue?

**Comment by e-d-n-a** [comment]
I'm not sure, if pyffms2 is supposed to work for macOS and Linux too (atm)
and the pythoncom-issue is not related to those platforms, as it is Windows-specific.
Yet, I just saw the [failing actions for Linux and macOS](https://github.com/bubblesub/pyffms2/actions/runs/557851271).

I see that ["ffms2" is cross-platform and only complicated to compile on Windows.](https://github.com/FFMS/ffms2/blob/master/doc/ffms2-api.md#compilation)

Do you compile "ffms2" for Windows yourself to be included in the wheel?
I used the [binary-release from the ffms2-GitHub](https://github.com/FFMS/ffms2/releases/download/2.40/ffms2-2.40-msvc.7z) with Python 3.8.7 and it works!
