### ISSUE TITLE
Broken test suite

### ISSUE THREAD

**Issue by lachs0r** [bubblesub/pyffms2#3]
The tests currently crash because an invalid error handling value is passed at 
https://github.com/rr-/pyffms2/blob/65a45c500d0bca19248db8014734e676a21ab2ef/test.py#L35

With that fixed, FFMS2 2.23.1 still fails with `Audio track contains no audio frames`. I have no idea why.

Also, the use of non-free codecs is problematic — some distributions cannot run the test suite with their main package sources.

**Comment by rr-** [comment]
Thanks, I'll try to look to it but please note I'll be away for the upcoming week. What codecs do you think the test files should use?

**Comment by lachs0r** [comment]
On Saturday, July 6, 2019 12:32:29 AM CEST Marcin Kurczewski wrote:
> Thanks, I'll try to look to it but please note I'll be away for the upcoming
> week. What codecs do you think the test files should use?

No problem. A list of suitable codecs can be found here:
https://build.opensuse.org/package/view_file/multimedia:libs/ffmpeg-4/enable_decoders?expand=1

**Comment by rr-** [comment]
@lachs0r I swapped the video for a smaller one, hopefully suitable for bundling with the package (around ~700K), encoded with vp9 and aac. I have also rewritten the tests to conform with the new API. Let me know if this works for you. I was unable ro reproduce the audio frames issue.

**Comment by rr-** [comment]
Closing, if you run into "With that fixed, FFMS2 2.23.1 still fails with Audio track contains no audio frames. I have no idea why." we'll debug it later

**Comment by lachs0r** [comment]
Well this seems to work now, but I run into this:

```
[   12s] ======================================================================
[   12s] FAIL: test_sample_video (__main__.TestFFMS2)
[   12s] ----------------------------------------------------------------------
[   12s] Traceback (most recent call last):
[   12s]   File "test.py", line 56, in test_sample_video
[   12s]     self.assertEqual(audio_source.properties.NumSamples, 664597)
[   12s] AssertionError: 664586 != 664597
```

**Comment by Luni-4** [comment]
@lachs0r 

Unfortunately, as you can see from the CI tests, the test suit is still broken. Need to compile `FFmpeg` from scratch instead of using not updated packages and try to find the error.

**Comment by lachs0r** [comment]
Maybe you can try using the Docker container I build for mpv’s build tests? I’ve just added pyffms2’s dependencies to it, so it should just work. It is based on openSUSE Tumbleweed, so packages should be mostly up to date.

```
registry.cirno.systems/kiwi/containers/mpv-ci:stable-deps
```

**Comment by Luni-4** [comment]
What I found strange is that your test passes on CI, but not from your part. Could you please try `ffms2/data/ffmsinfo.cpp` using your Docker container? Let's see if we get the same error or not. Thanks in advance!

**Comment by Luni-4** [comment]
@lachs0r 

CI tests are now fixed and I've also discovered that the packages were updated. 

For what concerns your problem, which system are you on? How can I reproduce it? Thanks in advance for your info!

**Comment by lachs0r** [comment]
I run openSUSE Tumbleweed (more specifically, I am packaging pyffms2 on OBS, which means I am using the stock distro packages for FFmpeg/FFMS2 — currently 4.2.1/2.23.1). The container I’ve linked should have everything you need, and is automatically kept in sync with the distro repositories.

**Comment by Luni-4** [comment]
Ok, I will try to run that container in order to find the problem. Just a couple of additional questions:

- How did you solve the initial crash? Have you just updated the `FFmpeg/ffms2` packages?
- Have you tried to install `pyffms2` using this command: `pip3 install .` ?

**Comment by Luni-4** [comment]
@lachs0r 

I fiddled with your container, if you build and install the `ffms2` master branch, both `ffmsinfo.cpp `and `test.py` succeed. 

```
zypper in autoconf automake libtool make
git clone https://github.com/FFMS/ffms2
cd ffms2
./configure --disable-dependency-tracking --prefix=/usr
make 
make install
mv -f /usr/lib/libffms2.so /usr/lib/libffms2.so.4 /usr/lib/libffms2.so.4.0.0 /usr/lib64
```

**Comment by lachs0r** [comment]
On Dienstag, 24. Dezember 2019 08:06:38 PST Luni-4 wrote:
> @lachs0r
> 
> I fiddled with your container, if you build and install the `ffms2` master
> branch, both `ffmsinfo.cpp `and `test.py` succeed.
> 
> ```
> zypper in autoconf automake libtool make
> git clone https://github.com/FFMS/ffms2
> cd ffms2
> ./configure --disable-dependency-tracking --prefix=/usr
> make
> make install
> mv -f /usr/lib/libffms2.so /usr/lib/libffms2.so.4 /usr/lib/libffms2.so.4.0.0
> /usr/lib64 ```

Okay, I guess that means I’ll have to update openSUSE’s FFMS2 package to a git 
snapshot because upstream isn’t making releases anymore?

**Comment by Luni-4** [comment]
> Okay, I guess that means I’ll have to update openSUSE’s FFMS2 package to a git snapshot because upstream isn’t making releases anymore?

Yep :)

**Comment by lachs0r** [comment]
On Tuesday, December 24, 2019 8:10:11 AM PST Luni-4 wrote:
> > Okay, I guess that means I’ll have to update openSUSE’s FFMS2 package to a
> > git snapshot because upstream isn’t making releases anymore?
> 
> Yep :)
> 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/bubblesub/pyffms2/issues/3#issuecomment-568772642

Done, will report back once it’s in Factory and can be packaged against.

**Comment by Luni-4** [comment]
> Done, will report back once it’s in Factory and can be packaged against.

Perfect!

**Comment by Luni-4** [comment]
The problem should be fixed, if it persists, feel free to reopen it @lachs0r :)
